// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for ConversationChannel.
const (
	ConversationChannelInstagram   ConversationChannel = "instagram"
	ConversationChannelMessenger   ConversationChannel = "messenger"
	ConversationChannelTelegramBot ConversationChannel = "telegram_bot"
	ConversationChannelWaba        ConversationChannel = "waba"
	ConversationChannelWhatsmeow   ConversationChannel = "whatsmeow"
)

// Valid indicates whether the value is a known member of the ConversationChannel enum.
func (e ConversationChannel) Valid() bool {
	switch e {
	case ConversationChannelInstagram:
		return true
	case ConversationChannelMessenger:
		return true
	case ConversationChannelTelegramBot:
		return true
	case ConversationChannelWaba:
		return true
	case ConversationChannelWhatsmeow:
		return true
	default:
		return false
	}
}

// Defines values for ConversationStatus.
const (
	Open     ConversationStatus = "open"
	Pending  ConversationStatus = "pending"
	Resolved ConversationStatus = "resolved"
)

// Valid indicates whether the value is a known member of the ConversationStatus enum.
func (e ConversationStatus) Valid() bool {
	switch e {
	case Open:
		return true
	case Pending:
		return true
	case Resolved:
		return true
	default:
		return false
	}
}

// Defines values for MessageDirection.
const (
	Inbound  MessageDirection = "inbound"
	Outbound MessageDirection = "outbound"
)

// Valid indicates whether the value is a known member of the MessageDirection enum.
func (e MessageDirection) Valid() bool {
	switch e {
	case Inbound:
		return true
	case Outbound:
		return true
	default:
		return false
	}
}

// Defines values for MessageStatus.
const (
	Notified MessageStatus = "notified"
	Received MessageStatus = "received"
	Routed   MessageStatus = "routed"
)

// Valid indicates whether the value is a known member of the MessageStatus enum.
func (e MessageStatus) Valid() bool {
	switch e {
	case Notified:
		return true
	case Received:
		return true
	case Routed:
		return true
	default:
		return false
	}
}

// Defines values for OutboundMessageChannel.
const (
	OutboundMessageChannelInstagram   OutboundMessageChannel = "instagram"
	OutboundMessageChannelMessenger   OutboundMessageChannel = "messenger"
	OutboundMessageChannelTelegramBot OutboundMessageChannel = "telegram_bot"
	OutboundMessageChannelWaba        OutboundMessageChannel = "waba"
	OutboundMessageChannelWhatsmeow   OutboundMessageChannel = "whatsmeow"
)

// Valid indicates whether the value is a known member of the OutboundMessageChannel enum.
func (e OutboundMessageChannel) Valid() bool {
	switch e {
	case OutboundMessageChannelInstagram:
		return true
	case OutboundMessageChannelMessenger:
		return true
	case OutboundMessageChannelTelegramBot:
		return true
	case OutboundMessageChannelWaba:
		return true
	case OutboundMessageChannelWhatsmeow:
		return true
	default:
		return false
	}
}

// Defines values for OutboundMessageType.
const (
	Audio    OutboundMessageType = "audio"
	Button   OutboundMessageType = "button"
	Document OutboundMessageType = "document"
	Image    OutboundMessageType = "image"
	Location OutboundMessageType = "location"
	Reaction OutboundMessageType = "reaction"
	Sticker  OutboundMessageType = "sticker"
	System   OutboundMessageType = "system"
	Template OutboundMessageType = "template"
	Text     OutboundMessageType = "text"
	Video    OutboundMessageType = "video"
)

// Valid indicates whether the value is a known member of the OutboundMessageType enum.
func (e OutboundMessageType) Valid() bool {
	switch e {
	case Audio:
		return true
	case Button:
		return true
	case Document:
		return true
	case Image:
		return true
	case Location:
		return true
	case Reaction:
		return true
	case Sticker:
		return true
	case System:
		return true
	case Template:
		return true
	case Text:
		return true
	case Video:
		return true
	default:
		return false
	}
}

// Defines values for QRCodeResponseProvider.
const (
	QRCodeResponseProviderWhatsmeow QRCodeResponseProvider = "whatsmeow"
)

// Valid indicates whether the value is a known member of the QRCodeResponseProvider enum.
func (e QRCodeResponseProvider) Valid() bool {
	switch e {
	case QRCodeResponseProviderWhatsmeow:
		return true
	default:
		return false
	}
}

// Defines values for ChannelHealthParamsChannel.
const (
	ChannelHealthParamsChannelInstagram   ChannelHealthParamsChannel = "instagram"
	ChannelHealthParamsChannelMessenger   ChannelHealthParamsChannel = "messenger"
	ChannelHealthParamsChannelTelegramBot ChannelHealthParamsChannel = "telegram_bot"
	ChannelHealthParamsChannelWaba        ChannelHealthParamsChannel = "waba"
	ChannelHealthParamsChannelWhatsmeow   ChannelHealthParamsChannel = "whatsmeow"
)

// Valid indicates whether the value is a known member of the ChannelHealthParamsChannel enum.
func (e ChannelHealthParamsChannel) Valid() bool {
	switch e {
	case ChannelHealthParamsChannelInstagram:
		return true
	case ChannelHealthParamsChannelMessenger:
		return true
	case ChannelHealthParamsChannelTelegramBot:
		return true
	case ChannelHealthParamsChannelWaba:
		return true
	case ChannelHealthParamsChannelWhatsmeow:
		return true
	default:
		return false
	}
}

// ActionAck defines model for ActionAck.
type ActionAck struct {
	Action    *string `json:"action,omitempty"`
	MessageId *string `json:"message_id,omitempty"`
	Status    *string `json:"status,omitempty"`
}

// ChannelHealth defines model for ChannelHealth.
type ChannelHealth struct {
	Channel *string `json:"channel,omitempty"`
	Error   *string `json:"error,omitempty"`
	Phase   *string `json:"phase,omitempty"`
	Status  *string `json:"status,omitempty"`
}

// Conversation defines model for Conversation.
type Conversation struct {
	AssignedAgent *string              `json:"assigned_agent,omitempty"`
	Channel       *ConversationChannel `json:"channel,omitempty"`
	ContactId     *openapi_types.UUID  `json:"contact_id,omitempty"`
	CreatedAt     *time.Time           `json:"created_at,omitempty"`
	ExternalId    *string              `json:"external_id,omitempty"`
	Id            *openapi_types.UUID  `json:"id,omitempty"`
	Status        *ConversationStatus  `json:"status,omitempty"`
	TenantId      *openapi_types.UUID  `json:"tenant_id,omitempty"`
	UpdatedAt     *time.Time           `json:"updated_at,omitempty"`
}

// ConversationChannel defines model for Conversation.Channel.
type ConversationChannel string

// ConversationStatus defines model for Conversation.Status.
type ConversationStatus string

// ConversationList defines model for ConversationList.
type ConversationList struct {
	Conversations *[]Conversation `json:"conversations,omitempty"`
	Total         *int            `json:"total,omitempty"`
}

// EditRequest defines model for EditRequest.
type EditRequest struct {
	Channel          string  `json:"channel"`
	ContactId        *string `json:"contact_id,omitempty"`
	ConversationId   *string `json:"conversation_id,omitempty"`
	NewBody          string  `json:"new_body"`
	PeerId           string  `json:"peer_id"`
	TargetProviderId string  `json:"target_provider_id"`
}

// Message defines model for Message.
type Message struct {
	Body           *string                 `json:"body,omitempty"`
	Channel        *string                 `json:"channel,omitempty"`
	ContactId      *openapi_types.UUID     `json:"contact_id,omitempty"`
	ConversationId *openapi_types.UUID     `json:"conversation_id,omitempty"`
	CreatedAt      *time.Time              `json:"created_at,omitempty"`
	Direction      *MessageDirection       `json:"direction,omitempty"`
	Id             *openapi_types.UUID     `json:"id,omitempty"`
	Metadata       *map[string]interface{} `json:"metadata,omitempty"`
	ProviderMsgId  *string                 `json:"provider_msg_id,omitempty"`
	Status         *MessageStatus          `json:"status,omitempty"`
	TenantId       *openapi_types.UUID     `json:"tenant_id,omitempty"`
	Type           *string                 `json:"type,omitempty"`
}

// MessageDirection defines model for Message.Direction.
type MessageDirection string

// MessageStatus defines model for Message.Status.
type MessageStatus string

// MessageList defines model for MessageList.
type MessageList struct {
	Messages *[]Message `json:"messages,omitempty"`
	Total    *int       `json:"total,omitempty"`
}

// MetaWebhookPayload Simplified shape — real payload is much larger
type MetaWebhookPayload struct {
	Entry  *[]map[string]interface{} `json:"entry,omitempty"`
	Object *string                   `json:"object,omitempty"`
}

// NotImplemented defines model for NotImplemented.
type NotImplemented struct {
	Error   *string `json:"error,omitempty"`
	Message *string `json:"message,omitempty"`
	Phase   *string `json:"phase,omitempty"`
}

// OutboundMessage defines model for OutboundMessage.
type OutboundMessage struct {
	Body           string                  `json:"body"`
	Channel        OutboundMessageChannel  `json:"channel"`
	ContactId      *openapi_types.UUID     `json:"contact_id,omitempty"`
	ConversationId openapi_types.UUID      `json:"conversation_id"`
	Metadata       *map[string]interface{} `json:"metadata,omitempty"`
	PeerId         string                  `json:"peer_id"`
	Type           OutboundMessageType     `json:"type"`
}

// OutboundMessageChannel defines model for OutboundMessage.Channel.
type OutboundMessageChannel string

// OutboundMessageType defines model for OutboundMessage.Type.
type OutboundMessageType string

// OutboundMessageSent defines model for OutboundMessageSent.
type OutboundMessageSent struct {
	Channel   *string             `json:"channel,omitempty"`
	CreatedAt *time.Time          `json:"created_at,omitempty"`
	MessageId *openapi_types.UUID `json:"message_id,omitempty"`
	Status    *string             `json:"status,omitempty"`
}

// QRCodeResponse defines model for QRCodeResponse.
type QRCodeResponse struct {
	Provider *QRCodeResponseProvider `json:"provider,omitempty"`

	// Qr QR code string (base64-friendly)
	Qr     *string             `json:"qr,omitempty"`
	Tenant *openapi_types.UUID `json:"tenant,omitempty"`
}

// QRCodeResponseProvider defines model for QRCodeResponse.Provider.
type QRCodeResponseProvider string

// ReactionRequest defines model for ReactionRequest.
type ReactionRequest struct {
	Channel          string  `json:"channel"`
	ContactId        *string `json:"contact_id,omitempty"`
	ConversationId   *string `json:"conversation_id,omitempty"`
	Emoji            string  `json:"emoji"`
	PeerId           string  `json:"peer_id"`
	TargetProviderId string  `json:"target_provider_id"`
}

// RevokeRequest defines model for RevokeRequest.
type RevokeRequest struct {
	Channel          string  `json:"channel"`
	ContactId        *string `json:"contact_id,omitempty"`
	ConversationId   *string `json:"conversation_id,omitempty"`
	PeerId           string  `json:"peer_id"`
	TargetProviderId string  `json:"target_provider_id"`
}

// TelegramUpdate defines model for TelegramUpdate.
type TelegramUpdate struct {
	Message  *map[string]interface{} `json:"message,omitempty"`
	UpdateId *int                    `json:"update_id,omitempty"`
}

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ChannelHealthParamsChannel defines parameters for ChannelHealth.
type ChannelHealthParamsChannel string

// AssignConversationJSONBody defines parameters for AssignConversation.
type AssignConversationJSONBody struct {
	AgentId string `json:"agent_id"`
}

// ListMessagesParams defines parameters for ListMessages.
type ListMessagesParams struct {
	ConversationId openapi_types.UUID `form:"conversation_id" json:"conversation_id"`
}

// AssignConversationJSONRequestBody defines body for AssignConversation for application/json ContentType.
type AssignConversationJSONRequestBody AssignConversationJSONBody

// PostMessageJSONRequestBody defines body for PostMessage for application/json ContentType.
type PostMessageJSONRequestBody = OutboundMessage

// RevokeMessageJSONRequestBody defines body for RevokeMessage for application/json ContentType.
type RevokeMessageJSONRequestBody = RevokeRequest

// EditMessageJSONRequestBody defines body for EditMessage for application/json ContentType.
type EditMessageJSONRequestBody = EditRequest

// PostReactionJSONRequestBody defines body for PostReaction for application/json ContentType.
type PostReactionJSONRequestBody = ReactionRequest

// ReceiveMetaWebhookJSONRequestBody defines body for ReceiveMetaWebhook for application/json ContentType.
type ReceiveMetaWebhookJSONRequestBody = MetaWebhookPayload

// ReceiveTelegramWebhookJSONRequestBody defines body for ReceiveTelegramWebhook for application/json ContentType.
type ReceiveTelegramWebhookJSONRequestBody = TelegramUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get the current WhatsMeow QR code for pairing (Fase 4)
	// (GET /api/channels/whatsmeow/qrcode)
	WhatsmeowQRCode(ctx echo.Context) error
	// Health of a channel (Fase 4: whatsmeow é real, não stub)
	// (GET /api/channels/{channel}/health)
	ChannelHealth(ctx echo.Context, channel ChannelHealthParamsChannel) error
	// List conversations of the current tenant
	// (GET /api/conversations)
	ListConversations(ctx echo.Context) error
	// Assign a conversation to an agent (Fase 2: just sets the field)
	// (POST /api/conversations/{id}/assign)
	AssignConversation(ctx echo.Context, id openapi_types.UUID) error
	// Mark a conversation as resolved
	// (POST /api/conversations/{id}/resolve)
	ResolveConversation(ctx echo.Context, id openapi_types.UUID) error
	// List messages of a conversation
	// (GET /api/messages)
	ListMessages(ctx echo.Context, params ListMessagesParams) error
	// Send a message (Fase 3 — real, queues to outbox)
	// (POST /api/messages)
	PostMessage(ctx echo.Context) error
	// Revoke a sent message (D6: ActionRevoke)
	// (DELETE /api/messages/{id})
	RevokeMessage(ctx echo.Context, id openapi_types.UUID) error
	// Edit a sent message (D6: ActionEdit)
	// (PATCH /api/messages/{id})
	EditMessage(ctx echo.Context, id openapi_types.UUID) error
	// Add a reaction to a message (D6)
	// (POST /api/messages/{id}/reactions)
	PostReaction(ctx echo.Context, id openapi_types.UUID) error
	// Health check
	// (GET /health)
	Health(ctx echo.Context) error
	// Prometheus metrics
	// (GET /metrics)
	Metrics(ctx echo.Context) error
	// Readiness check
	// (GET /readyz)
	Readiness(ctx echo.Context) error
	// Receive a Meta webhook (WABA / Instagram / Messenger)
	// (POST /webhooks/meta/{app_id})
	ReceiveMetaWebhook(ctx echo.Context, appId string) error
	// Receive a Telegram Bot webhook
	// (POST /webhooks/telegram/{tenant_id})
	ReceiveTelegramWebhook(ctx echo.Context, tenantId openapi_types.UUID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// WhatsmeowQRCode converts echo context to params.
func (w *ServerInterfaceWrapper) WhatsmeowQRCode(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.WhatsmeowQRCode(ctx)
	return err
}

// ChannelHealth converts echo context to params.
func (w *ServerInterfaceWrapper) ChannelHealth(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "channel" -------------
	var channel ChannelHealthParamsChannel

	err = runtime.BindStyledParameterWithOptions("simple", "channel", ctx.Param("channel"), &channel, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter channel: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ChannelHealth(ctx, channel)
	return err
}

// ListConversations converts echo context to params.
func (w *ServerInterfaceWrapper) ListConversations(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListConversations(ctx)
	return err
}

// AssignConversation converts echo context to params.
func (w *ServerInterfaceWrapper) AssignConversation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AssignConversation(ctx, id)
	return err
}

// ResolveConversation converts echo context to params.
func (w *ServerInterfaceWrapper) ResolveConversation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ResolveConversation(ctx, id)
	return err
}

// ListMessages converts echo context to params.
func (w *ServerInterfaceWrapper) ListMessages(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMessagesParams
	// ------------- Required query parameter "conversation_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "conversation_id", ctx.QueryParams(), &params.ConversationId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter conversation_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListMessages(ctx, params)
	return err
}

// PostMessage converts echo context to params.
func (w *ServerInterfaceWrapper) PostMessage(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostMessage(ctx)
	return err
}

// RevokeMessage converts echo context to params.
func (w *ServerInterfaceWrapper) RevokeMessage(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RevokeMessage(ctx, id)
	return err
}

// EditMessage converts echo context to params.
func (w *ServerInterfaceWrapper) EditMessage(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.EditMessage(ctx, id)
	return err
}

// PostReaction converts echo context to params.
func (w *ServerInterfaceWrapper) PostReaction(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostReaction(ctx, id)
	return err
}

// Health converts echo context to params.
func (w *ServerInterfaceWrapper) Health(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Health(ctx)
	return err
}

// Metrics converts echo context to params.
func (w *ServerInterfaceWrapper) Metrics(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Metrics(ctx)
	return err
}

// Readiness converts echo context to params.
func (w *ServerInterfaceWrapper) Readiness(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Readiness(ctx)
	return err
}

// ReceiveMetaWebhook converts echo context to params.
func (w *ServerInterfaceWrapper) ReceiveMetaWebhook(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "app_id" -------------
	var appId string

	err = runtime.BindStyledParameterWithOptions("simple", "app_id", ctx.Param("app_id"), &appId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter app_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ReceiveMetaWebhook(ctx, appId)
	return err
}

// ReceiveTelegramWebhook converts echo context to params.
func (w *ServerInterfaceWrapper) ReceiveTelegramWebhook(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "tenant_id" -------------
	var tenantId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tenant_id", ctx.Param("tenant_id"), &tenantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tenant_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ReceiveTelegramWebhook(ctx, tenantId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/api/channels/whatsmeow/qrcode", wrapper.WhatsmeowQRCode, options.OperationMiddlewares["whatsmeowQRCode"]...)
	router.GET(options.BaseURL+"/api/channels/:channel/health", wrapper.ChannelHealth, options.OperationMiddlewares["channelHealth"]...)
	router.GET(options.BaseURL+"/api/conversations", wrapper.ListConversations, options.OperationMiddlewares["listConversations"]...)
	router.POST(options.BaseURL+"/api/conversations/:id/assign", wrapper.AssignConversation, options.OperationMiddlewares["assignConversation"]...)
	router.POST(options.BaseURL+"/api/conversations/:id/resolve", wrapper.ResolveConversation, options.OperationMiddlewares["resolveConversation"]...)
	router.GET(options.BaseURL+"/api/messages", wrapper.ListMessages, options.OperationMiddlewares["listMessages"]...)
	router.POST(options.BaseURL+"/api/messages", wrapper.PostMessage, options.OperationMiddlewares["postMessage"]...)
	router.DELETE(options.BaseURL+"/api/messages/:id", wrapper.RevokeMessage, options.OperationMiddlewares["revokeMessage"]...)
	router.PATCH(options.BaseURL+"/api/messages/:id", wrapper.EditMessage, options.OperationMiddlewares["editMessage"]...)
	router.POST(options.BaseURL+"/api/messages/:id/reactions", wrapper.PostReaction, options.OperationMiddlewares["postReaction"]...)
	router.GET(options.BaseURL+"/health", wrapper.Health, options.OperationMiddlewares["health"]...)
	router.GET(options.BaseURL+"/metrics", wrapper.Metrics, options.OperationMiddlewares["metrics"]...)
	router.GET(options.BaseURL+"/readyz", wrapper.Readiness, options.OperationMiddlewares["readiness"]...)
	router.POST(options.BaseURL+"/webhooks/meta/:app_id", wrapper.ReceiveMetaWebhook, options.OperationMiddlewares["receiveMetaWebhook"]...)
	router.POST(options.BaseURL+"/webhooks/telegram/:tenant_id", wrapper.ReceiveTelegramWebhook, options.OperationMiddlewares["receiveTelegramWebhook"]...)

}
