// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for ConversationChannel.
const (
	ConversationChannelInstagram   ConversationChannel = "instagram"
	ConversationChannelMessenger   ConversationChannel = "messenger"
	ConversationChannelTelegramBot ConversationChannel = "telegram_bot"
	ConversationChannelWaba        ConversationChannel = "waba"
	ConversationChannelWhatsmeow   ConversationChannel = "whatsmeow"
)

// Valid indicates whether the value is a known member of the ConversationChannel enum.
func (e ConversationChannel) Valid() bool {
	switch e {
	case ConversationChannelInstagram:
		return true
	case ConversationChannelMessenger:
		return true
	case ConversationChannelTelegramBot:
		return true
	case ConversationChannelWaba:
		return true
	case ConversationChannelWhatsmeow:
		return true
	default:
		return false
	}
}

// Defines values for ConversationStatus.
const (
	Open     ConversationStatus = "open"
	Pending  ConversationStatus = "pending"
	Resolved ConversationStatus = "resolved"
)

// Valid indicates whether the value is a known member of the ConversationStatus enum.
func (e ConversationStatus) Valid() bool {
	switch e {
	case Open:
		return true
	case Pending:
		return true
	case Resolved:
		return true
	default:
		return false
	}
}

// Defines values for MessageDirection.
const (
	Inbound  MessageDirection = "inbound"
	Outbound MessageDirection = "outbound"
)

// Valid indicates whether the value is a known member of the MessageDirection enum.
func (e MessageDirection) Valid() bool {
	switch e {
	case Inbound:
		return true
	case Outbound:
		return true
	default:
		return false
	}
}

// Defines values for MessageStatus.
const (
	Notified MessageStatus = "notified"
	Received MessageStatus = "received"
	Routed   MessageStatus = "routed"
)

// Valid indicates whether the value is a known member of the MessageStatus enum.
func (e MessageStatus) Valid() bool {
	switch e {
	case Notified:
		return true
	case Received:
		return true
	case Routed:
		return true
	default:
		return false
	}
}

// Defines values for OutboundMessageChannel.
const (
	OutboundMessageChannelInstagram   OutboundMessageChannel = "instagram"
	OutboundMessageChannelMessenger   OutboundMessageChannel = "messenger"
	OutboundMessageChannelTelegramBot OutboundMessageChannel = "telegram_bot"
	OutboundMessageChannelWaba        OutboundMessageChannel = "waba"
	OutboundMessageChannelWhatsmeow   OutboundMessageChannel = "whatsmeow"
)

// Valid indicates whether the value is a known member of the OutboundMessageChannel enum.
func (e OutboundMessageChannel) Valid() bool {
	switch e {
	case OutboundMessageChannelInstagram:
		return true
	case OutboundMessageChannelMessenger:
		return true
	case OutboundMessageChannelTelegramBot:
		return true
	case OutboundMessageChannelWaba:
		return true
	case OutboundMessageChannelWhatsmeow:
		return true
	default:
		return false
	}
}

// Defines values for OutboundMessageType.
const (
	Audio    OutboundMessageType = "audio"
	Button   OutboundMessageType = "button"
	Document OutboundMessageType = "document"
	Image    OutboundMessageType = "image"
	Location OutboundMessageType = "location"
	Reaction OutboundMessageType = "reaction"
	Sticker  OutboundMessageType = "sticker"
	System   OutboundMessageType = "system"
	Template OutboundMessageType = "template"
	Text     OutboundMessageType = "text"
	Video    OutboundMessageType = "video"
)

// Valid indicates whether the value is a known member of the OutboundMessageType enum.
func (e OutboundMessageType) Valid() bool {
	switch e {
	case Audio:
		return true
	case Button:
		return true
	case Document:
		return true
	case Image:
		return true
	case Location:
		return true
	case Reaction:
		return true
	case Sticker:
		return true
	case System:
		return true
	case Template:
		return true
	case Text:
		return true
	case Video:
		return true
	default:
		return false
	}
}

// Defines values for QRCodeResponseProvider.
const (
	QRCodeResponseProviderWhatsmeow QRCodeResponseProvider = "whatsmeow"
)

// Valid indicates whether the value is a known member of the QRCodeResponseProvider enum.
func (e QRCodeResponseProvider) Valid() bool {
	switch e {
	case QRCodeResponseProviderWhatsmeow:
		return true
	default:
		return false
	}
}

// Defines values for ChannelHealthParamsChannel.
const (
	ChannelHealthParamsChannelInstagram   ChannelHealthParamsChannel = "instagram"
	ChannelHealthParamsChannelMessenger   ChannelHealthParamsChannel = "messenger"
	ChannelHealthParamsChannelTelegramBot ChannelHealthParamsChannel = "telegram_bot"
	ChannelHealthParamsChannelWaba        ChannelHealthParamsChannel = "waba"
	ChannelHealthParamsChannelWhatsmeow   ChannelHealthParamsChannel = "whatsmeow"
)

// Valid indicates whether the value is a known member of the ChannelHealthParamsChannel enum.
func (e ChannelHealthParamsChannel) Valid() bool {
	switch e {
	case ChannelHealthParamsChannelInstagram:
		return true
	case ChannelHealthParamsChannelMessenger:
		return true
	case ChannelHealthParamsChannelTelegramBot:
		return true
	case ChannelHealthParamsChannelWaba:
		return true
	case ChannelHealthParamsChannelWhatsmeow:
		return true
	default:
		return false
	}
}

// ActionAck defines model for ActionAck.
type ActionAck struct {
	Action    *string `json:"action,omitempty"`
	MessageId *string `json:"message_id,omitempty"`
	Status    *string `json:"status,omitempty"`
}

// ChannelHealth defines model for ChannelHealth.
type ChannelHealth struct {
	Channel *string `json:"channel,omitempty"`
	Error   *string `json:"error,omitempty"`
	Phase   *string `json:"phase,omitempty"`
	Status  *string `json:"status,omitempty"`
}

// Conversation defines model for Conversation.
type Conversation struct {
	AssignedAgent *string              `json:"assigned_agent,omitempty"`
	Channel       *ConversationChannel `json:"channel,omitempty"`
	ContactId     *openapi_types.UUID  `json:"contact_id,omitempty"`
	CreatedAt     *time.Time           `json:"created_at,omitempty"`
	ExternalId    *string              `json:"external_id,omitempty"`
	Id            *openapi_types.UUID  `json:"id,omitempty"`
	Status        *ConversationStatus  `json:"status,omitempty"`
	TenantId      *openapi_types.UUID  `json:"tenant_id,omitempty"`
	UpdatedAt     *time.Time           `json:"updated_at,omitempty"`
}

// ConversationChannel defines model for Conversation.Channel.
type ConversationChannel string

// ConversationStatus defines model for Conversation.Status.
type ConversationStatus string

// ConversationList defines model for ConversationList.
type ConversationList struct {
	Conversations *[]Conversation `json:"conversations,omitempty"`
	Total         *int            `json:"total,omitempty"`
}

// EditRequest defines model for EditRequest.
type EditRequest struct {
	Channel          string  `json:"channel"`
	ContactId        *string `json:"contact_id,omitempty"`
	ConversationId   *string `json:"conversation_id,omitempty"`
	NewBody          string  `json:"new_body"`
	PeerId           string  `json:"peer_id"`
	TargetProviderId string  `json:"target_provider_id"`
}

// Message defines model for Message.
type Message struct {
	Body           *string                 `json:"body,omitempty"`
	Channel        *string                 `json:"channel,omitempty"`
	ContactId      *openapi_types.UUID     `json:"contact_id,omitempty"`
	ConversationId *openapi_types.UUID     `json:"conversation_id,omitempty"`
	CreatedAt      *time.Time              `json:"created_at,omitempty"`
	Direction      *MessageDirection       `json:"direction,omitempty"`
	Id             *openapi_types.UUID     `json:"id,omitempty"`
	Metadata       *map[string]interface{} `json:"metadata,omitempty"`
	ProviderMsgId  *string                 `json:"provider_msg_id,omitempty"`
	Status         *MessageStatus          `json:"status,omitempty"`
	TenantId       *openapi_types.UUID     `json:"tenant_id,omitempty"`
	Type           *string                 `json:"type,omitempty"`
}

// MessageDirection defines model for Message.Direction.
type MessageDirection string

// MessageStatus defines model for Message.Status.
type MessageStatus string

// MessageList defines model for MessageList.
type MessageList struct {
	Messages *[]Message `json:"messages,omitempty"`
	Total    *int       `json:"total,omitempty"`
}

// MetaWebhookPayload Simplified shape — real payload is much larger
type MetaWebhookPayload struct {
	Entry  *[]map[string]interface{} `json:"entry,omitempty"`
	Object *string                   `json:"object,omitempty"`
}

// NotImplemented defines model for NotImplemented.
type NotImplemented struct {
	Error   *string `json:"error,omitempty"`
	Message *string `json:"message,omitempty"`
	Phase   *string `json:"phase,omitempty"`
}

// OutboundMessage defines model for OutboundMessage.
type OutboundMessage struct {
	Body           string                  `json:"body"`
	Channel        OutboundMessageChannel  `json:"channel"`
	ContactId      *openapi_types.UUID     `json:"contact_id,omitempty"`
	ConversationId openapi_types.UUID      `json:"conversation_id"`
	Metadata       *map[string]interface{} `json:"metadata,omitempty"`
	PeerId         string                  `json:"peer_id"`
	Type           OutboundMessageType     `json:"type"`
}

// OutboundMessageChannel defines model for OutboundMessage.Channel.
type OutboundMessageChannel string

// OutboundMessageType defines model for OutboundMessage.Type.
type OutboundMessageType string

// OutboundMessageSent defines model for OutboundMessageSent.
type OutboundMessageSent struct {
	Channel   *string             `json:"channel,omitempty"`
	CreatedAt *time.Time          `json:"created_at,omitempty"`
	MessageId *openapi_types.UUID `json:"message_id,omitempty"`
	Status    *string             `json:"status,omitempty"`
}

// QRCodeResponse defines model for QRCodeResponse.
type QRCodeResponse struct {
	Provider *QRCodeResponseProvider `json:"provider,omitempty"`

	// Qr QR code string (base64-friendly)
	Qr     *string             `json:"qr,omitempty"`
	Tenant *openapi_types.UUID `json:"tenant,omitempty"`
}

// QRCodeResponseProvider defines model for QRCodeResponse.Provider.
type QRCodeResponseProvider string

// ReactionRequest defines model for ReactionRequest.
type ReactionRequest struct {
	Channel          string  `json:"channel"`
	ContactId        *string `json:"contact_id,omitempty"`
	ConversationId   *string `json:"conversation_id,omitempty"`
	Emoji            string  `json:"emoji"`
	PeerId           string  `json:"peer_id"`
	TargetProviderId string  `json:"target_provider_id"`
}

// RevokeRequest defines model for RevokeRequest.
type RevokeRequest struct {
	Channel          string  `json:"channel"`
	ContactId        *string `json:"contact_id,omitempty"`
	ConversationId   *string `json:"conversation_id,omitempty"`
	PeerId           string  `json:"peer_id"`
	TargetProviderId string  `json:"target_provider_id"`
}

// TelegramUpdate defines model for TelegramUpdate.
type TelegramUpdate struct {
	Message  *map[string]interface{} `json:"message,omitempty"`
	UpdateId *int                    `json:"update_id,omitempty"`
}

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ChannelHealthParamsChannel defines parameters for ChannelHealth.
type ChannelHealthParamsChannel string

// AssignConversationJSONBody defines parameters for AssignConversation.
type AssignConversationJSONBody struct {
	AgentId string `json:"agent_id"`
}

// ListMessagesParams defines parameters for ListMessages.
type ListMessagesParams struct {
	ConversationId openapi_types.UUID `form:"conversation_id" json:"conversation_id"`
}

// AssignConversationJSONRequestBody defines body for AssignConversation for application/json ContentType.
type AssignConversationJSONRequestBody AssignConversationJSONBody

// PostMessageJSONRequestBody defines body for PostMessage for application/json ContentType.
type PostMessageJSONRequestBody = OutboundMessage

// RevokeMessageJSONRequestBody defines body for RevokeMessage for application/json ContentType.
type RevokeMessageJSONRequestBody = RevokeRequest

// EditMessageJSONRequestBody defines body for EditMessage for application/json ContentType.
type EditMessageJSONRequestBody = EditRequest

// PostReactionJSONRequestBody defines body for PostReaction for application/json ContentType.
type PostReactionJSONRequestBody = ReactionRequest

// ReceiveMetaWebhookJSONRequestBody defines body for ReceiveMetaWebhook for application/json ContentType.
type ReceiveMetaWebhookJSONRequestBody = MetaWebhookPayload

// ReceiveTelegramWebhookJSONRequestBody defines body for ReceiveTelegramWebhook for application/json ContentType.
type ReceiveTelegramWebhookJSONRequestBody = TelegramUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get the current WhatsMeow QR code for pairing (Fase 4)
	// (GET /api/channels/whatsmeow/qrcode)
	WhatsmeowQRCode(w http.ResponseWriter, r *http.Request)
	// Health of a channel (Fase 4: whatsmeow é real, não stub)
	// (GET /api/channels/{channel}/health)
	ChannelHealth(w http.ResponseWriter, r *http.Request, channel ChannelHealthParamsChannel)
	// List conversations of the current tenant
	// (GET /api/conversations)
	ListConversations(w http.ResponseWriter, r *http.Request)
	// Assign a conversation to an agent (Fase 2: just sets the field)
	// (POST /api/conversations/{id}/assign)
	AssignConversation(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Mark a conversation as resolved
	// (POST /api/conversations/{id}/resolve)
	ResolveConversation(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// List messages of a conversation
	// (GET /api/messages)
	ListMessages(w http.ResponseWriter, r *http.Request, params ListMessagesParams)
	// Send a message (Fase 3 — real, queues to outbox)
	// (POST /api/messages)
	PostMessage(w http.ResponseWriter, r *http.Request)
	// Revoke a sent message (D6: ActionRevoke)
	// (DELETE /api/messages/{id})
	RevokeMessage(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Edit a sent message (D6: ActionEdit)
	// (PATCH /api/messages/{id})
	EditMessage(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Add a reaction to a message (D6)
	// (POST /api/messages/{id}/reactions)
	PostReaction(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Health check
	// (GET /health)
	Health(w http.ResponseWriter, r *http.Request)
	// Prometheus metrics
	// (GET /metrics)
	Metrics(w http.ResponseWriter, r *http.Request)
	// Readiness check
	// (GET /readyz)
	Readiness(w http.ResponseWriter, r *http.Request)
	// Receive a Meta webhook (WABA / Instagram / Messenger)
	// (POST /webhooks/meta/{app_id})
	ReceiveMetaWebhook(w http.ResponseWriter, r *http.Request, appId string)
	// Receive a Telegram Bot webhook
	// (POST /webhooks/telegram/{tenant_id})
	ReceiveTelegramWebhook(w http.ResponseWriter, r *http.Request, tenantId openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get the current WhatsMeow QR code for pairing (Fase 4)
// (GET /api/channels/whatsmeow/qrcode)
func (_ Unimplemented) WhatsmeowQRCode(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health of a channel (Fase 4: whatsmeow é real, não stub)
// (GET /api/channels/{channel}/health)
func (_ Unimplemented) ChannelHealth(w http.ResponseWriter, r *http.Request, channel ChannelHealthParamsChannel) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List conversations of the current tenant
// (GET /api/conversations)
func (_ Unimplemented) ListConversations(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Assign a conversation to an agent (Fase 2: just sets the field)
// (POST /api/conversations/{id}/assign)
func (_ Unimplemented) AssignConversation(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Mark a conversation as resolved
// (POST /api/conversations/{id}/resolve)
func (_ Unimplemented) ResolveConversation(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List messages of a conversation
// (GET /api/messages)
func (_ Unimplemented) ListMessages(w http.ResponseWriter, r *http.Request, params ListMessagesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Send a message (Fase 3 — real, queues to outbox)
// (POST /api/messages)
func (_ Unimplemented) PostMessage(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Revoke a sent message (D6: ActionRevoke)
// (DELETE /api/messages/{id})
func (_ Unimplemented) RevokeMessage(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Edit a sent message (D6: ActionEdit)
// (PATCH /api/messages/{id})
func (_ Unimplemented) EditMessage(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a reaction to a message (D6)
// (POST /api/messages/{id}/reactions)
func (_ Unimplemented) PostReaction(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check
// (GET /health)
func (_ Unimplemented) Health(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Prometheus metrics
// (GET /metrics)
func (_ Unimplemented) Metrics(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Readiness check
// (GET /readyz)
func (_ Unimplemented) Readiness(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Receive a Meta webhook (WABA / Instagram / Messenger)
// (POST /webhooks/meta/{app_id})
func (_ Unimplemented) ReceiveMetaWebhook(w http.ResponseWriter, r *http.Request, appId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Receive a Telegram Bot webhook
// (POST /webhooks/telegram/{tenant_id})
func (_ Unimplemented) ReceiveTelegramWebhook(w http.ResponseWriter, r *http.Request, tenantId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// WhatsmeowQRCode operation middleware
func (siw *ServerInterfaceWrapper) WhatsmeowQRCode(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.WhatsmeowQRCode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ChannelHealth operation middleware
func (siw *ServerInterfaceWrapper) ChannelHealth(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "channel" -------------
	var channel ChannelHealthParamsChannel

	err = runtime.BindStyledParameterWithOptions("simple", "channel", chi.URLParam(r, "channel"), &channel, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channel", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ChannelHealth(w, r, channel)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListConversations operation middleware
func (siw *ServerInterfaceWrapper) ListConversations(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListConversations(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AssignConversation operation middleware
func (siw *ServerInterfaceWrapper) AssignConversation(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AssignConversation(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResolveConversation operation middleware
func (siw *ServerInterfaceWrapper) ResolveConversation(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResolveConversation(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMessages operation middleware
func (siw *ServerInterfaceWrapper) ListMessages(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMessagesParams

	// ------------- Required query parameter "conversation_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "conversation_id", r.URL.Query(), &params.ConversationId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "conversation_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "conversation_id", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMessages(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostMessage operation middleware
func (siw *ServerInterfaceWrapper) PostMessage(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostMessage(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeMessage operation middleware
func (siw *ServerInterfaceWrapper) RevokeMessage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeMessage(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EditMessage operation middleware
func (siw *ServerInterfaceWrapper) EditMessage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EditMessage(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostReaction operation middleware
func (siw *ServerInterfaceWrapper) PostReaction(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostReaction(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Health operation middleware
func (siw *ServerInterfaceWrapper) Health(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Health(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Metrics operation middleware
func (siw *ServerInterfaceWrapper) Metrics(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Metrics(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Readiness operation middleware
func (siw *ServerInterfaceWrapper) Readiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Readiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReceiveMetaWebhook operation middleware
func (siw *ServerInterfaceWrapper) ReceiveMetaWebhook(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "app_id" -------------
	var appId string

	err = runtime.BindStyledParameterWithOptions("simple", "app_id", chi.URLParam(r, "app_id"), &appId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "app_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReceiveMetaWebhook(w, r, appId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReceiveTelegramWebhook operation middleware
func (siw *ServerInterfaceWrapper) ReceiveTelegramWebhook(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "tenant_id" -------------
	var tenantId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tenant_id", chi.URLParam(r, "tenant_id"), &tenantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tenant_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReceiveTelegramWebhook(w, r, tenantId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/channels/whatsmeow/qrcode", wrapper.WhatsmeowQRCode)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/channels/{channel}/health", wrapper.ChannelHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/conversations", wrapper.ListConversations)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/conversations/{id}/assign", wrapper.AssignConversation)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/conversations/{id}/resolve", wrapper.ResolveConversation)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/messages", wrapper.ListMessages)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/messages", wrapper.PostMessage)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/messages/{id}", wrapper.RevokeMessage)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/messages/{id}", wrapper.EditMessage)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/messages/{id}/reactions", wrapper.PostReaction)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.Health)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/metrics", wrapper.Metrics)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readyz", wrapper.Readiness)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/webhooks/meta/{app_id}", wrapper.ReceiveMetaWebhook)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/webhooks/telegram/{tenant_id}", wrapper.ReceiveTelegramWebhook)
	})

	return r
}
